# Generated by Django 2.2.5 on 2019-09-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('short', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaturityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('practice_name', models.CharField(max_length=64, unique=True)),
                ('process_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=256, unique=True)),
                ('process', models.BooleanField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmcdb.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=64)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmcdb.Activity')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmcdb.Reference')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='capability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmcdb.Capability'),
        ),
        migrations.AddField(
            model_name='activity',
            name='maturity_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmmcdb.MaturityLevel'),
        ),
    ]
