# Generated by Django 3.0.2 on 2020-02-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmmcdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='text_id',
        ),
        migrations.AddField(
            model_name='practice',
            name='practice_number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='short',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
