name: Lint and Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check Style
      run: |
        black --check .
    - name: Lint with flake8
      run: |
        pip install flake8 flake8-django
        # Until we get the warnings under control, don't stop the CI pipeline.
        flake8 --exit-zero cmmcdb
    - name: Setup test database
      run: |
        python manage.py migrate
    - name: Run Django Tests
      run: |
        python -X dev manage.py test cmmcdb
